# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle',
            options={'verbose_name': 'Detalle', 'verbose_name_plural': 'Detalles'},
        ),
        migrations.AddField(
            model_name='recibo',
            name='fecha_vencimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
