# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('edificios', '0017_auto_20161205_1626'),
        ('pagos', '0003_auto_20161221_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeNoticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Detalle noticia',
                'verbose_name_plural': 'Detalles noticias',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Administrador')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.AddField(
            model_name='denoticia',
            name='idNoticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Noticia'),
        ),
        migrations.AddField(
            model_name='denoticia',
            name='idRecibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Recibo'),
        ),
        migrations.AddField(
            model_name='denoticia',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Unidad'),
        ),
    ]
