# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-27 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_auto_20161227_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'No visto'), (1, 'Visto'), (3, 'No visto 7 Dias')], default=0),
        ),
    ]
