# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0017_auto_20161205_1626'),
        ('pagos', '0005_auto_20161227_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='propiedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edificios.Propiedad'),
            preserve_default=False,
        ),
    ]
