# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_auto_20161228_1138'),
    ]

    operations = [
    ]
