# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interesAplicado', models.PositiveIntegerField()),
                ('valorinteres', models.BigIntegerField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='interes',
            name='idRecibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Recibo'),
        ),
    ]
