# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20161229_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('IdReciboDeuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Recibo')),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
            },
        ),
        migrations.AddField(
            model_name='detalle',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalle',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deuda',
            name='idDetalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Detalle'),
        ),
    ]
