# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0017_auto_20161205_1626'),
        ('pagos', '0003_auto_20161229_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edificios.Unidad'),
            preserve_default=False,
        ),
    ]
