# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-30 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_deuda_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecibosAuto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idRecibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Recibo')),
            ],
        ),
    ]
