# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0020_auto_20170110_1218'),
        ('pagos', '0005_recibosauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecibosPagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('no_comprobante', models.PositiveIntegerField()),
                ('pagador', models.CharField(max_length=100, verbose_name='RecibioDe')),
                ('suma', models.BigIntegerField()),
                ('enletras', models.CharField(max_length=200)),
                ('concepto', models.CharField(max_length=200)),
                ('forma_pago', models.PositiveIntegerField(choices=[(0, 'Cheque'), (1, 'Banco'), (3, 'Efectivo'), (4, 'Transferencia')], default=3)),
                ('referencia', models.CharField(max_length=50)),
                ('tipo', models.PositiveIntegerField(choices=[(0, 'PagoTotal'), (1, 'Abono')], default=2)),
                ('recibo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagos.Recibo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Unidad')),
            ],
        ),
    ]
