# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_recibospagos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibospagos',
            old_name='referencia',
            new_name='referencia1',
        ),
        migrations.AddField(
            model_name='recibospagos',
            name='referencia2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
