# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-19 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_auto_20170118_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recibospagos',
            options={'verbose_name': 'Recibo Pago', 'verbose_name_plural': 'Recibos Pagos'},
        ),
        migrations.AlterField(
            model_name='recibospagos',
            name='forma_pago',
            field=models.PositiveIntegerField(choices=[(0, 'Cheque'), (1, 'Banco'), (2, 'Efectivo'), (3, 'Transferencia')], default=2),
        ),
        migrations.AlterField(
            model_name='recibospagos',
            name='referencia1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recibospagos',
            name='referencia2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
