# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_auto_20170118_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecibosyComprobante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='recibospagos',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Recibo'),
        ),
        migrations.AddField(
            model_name='recibosycomprobante',
            name='comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.RecibosPagos'),
        ),
        migrations.AddField(
            model_name='recibosycomprobante',
            name='recibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Recibo'),
        ),
    ]
