# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0009_auto_20170120_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibosycomprobante',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(0, 'Pago'), (1, 'Abono')], default=0),
        ),
    ]
