# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0010_recibosycomprobante_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_inicial', models.PositiveIntegerField()),
                ('valor_abonado', models.PositiveIntegerField()),
                ('valor_restante', models.PositiveIntegerField()),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.Detalle')),
            ],
        ),
    ]
