# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0011_abonos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abonos',
            new_name='Abono',
        ),
    ]
