# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0020_auto_20170110_1218'),
        ('pagos', '0012_auto_20170120_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaExtraordinaria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.BigIntegerField()),
                ('cuotas', models.IntegerField()),
                ('tipo_cuota', models.IntegerField(choices=[(0, 'igualitaria'), (1, 'Coeficiente')], default=1)),
                ('estado', models.IntegerField(choices=[(0, 'finalizada'), (1, 'activa')], default=0)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaExtraUnidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.BigIntegerField()),
                ('cont_cuota', models.PositiveIntegerField()),
                ('idExtraordinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.CuotaExtraordinaria')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificios.Unidad')),
            ],
        ),
    ]
