# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0017_auto_20161205_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='propiedad',
            field=models.ForeignKey(default='mon-12390182093', on_delete=django.db.models.deletion.CASCADE, to='edificios.Propiedad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='valor_pago',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
