# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0018_auto_20170104_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='tipo',
            field=models.PositiveIntegerField(choices=[(1, 'Residencial'), (2, 'Comercial')], default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.PositiveIntegerField(verbose_name='Telefono'),
        ),
    ]
