# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0019_auto_20170110_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Residencial'), (2, 'Comercial')], default=1),
        ),
    ]
